### ISSUE TITLE
How to use access token and refresh access token automatically

### ISSUE THREAD

**Issue by jasondiazg** [wso2-extensions/identity-sdks-js#8]
**Description:**
There are no examples about how to use the access token in a API request and how the refresh token works?

**Suggested Labels:**
documentation, help

**Related Issues:**
[Get Access Token method accessibility](https://github.com/wso2-extensions/identity-sdks-js/issues/7)

**Comment by gayashanbc** [comment]
This issue is tracked from https://github.com/asgardio/asgardio-js-oidc-sdk/issues/17
